### ISSUE TITLE
How to consume generated stream?

### ISSUE THREAD

**Issue by astrowalker** [klaxa/mkvserver_mk2#10]
Thank you very much for this project!

I would like to create web page and display the stream generated by this server but currently I don't how. I use the last example (I had to add `-f matroska` to ffmpeg call) and in server output I don't see any hints how to consume the stream -- I am not even sure if the stream is correctly created, because I see periodically "Error or timeout, ret: -110" error.

So, my question is -- what is the minimal setup/example to consume the stream?

**Comment by klaxa** [comment]
Hi,

to consume the stream, use a mediaplayer (or any other http client) and read: http://\<address\>:8080/
For example, if you are running the server on the same machine: mpv http://localhost:8080

Regarding embedding videos into websites, this is currently not possible, as HTML5 does not support the full matroska spec. See also Issue #5 .
