### ISSUE TITLE
tcp://remote:12345: Invalid argument

### ISSUE THREAD

**Issue by weiwang999** [klaxa/mkvserver_mk2#19]
weiwang99@cs000061:~/ffmpeg-4.1.3$ ffmpeg -f x11grab -framerate 15 -s 1920x1080 -i :0.0 -c libx264 tcp://remote:12345
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 20160609
  configuration: --enable-libxcb
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
[x11grab @ 0x2ced5c0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, x11grab, from ':0.0':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1920x1080, 15 fps, 1000k tbr, 1000k tbn, 1000k tbc
[NULL @ 0x2cf5500] Unable to find a suitable output format for 'tcp://remote:12345'
tcp://remote:12345: Invalid argument

**Comment by klaxa** [comment]
This lacks '-f matroska'. Thanks for pointing out, will update the Readme.

**Comment by weiwang999** [comment]
weiwang99@cs000061:~/ffmpeg-4.1.3$ ffmpeg -f x11grab -framerate 15 -f matroska -s 1920x1080 -i :0.0 -c libx264 tcp://remote:12345
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 20160609
  configuration: --enable-libxcb
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
:0.0: Protocol not found
Did you mean file::0.0?

**Comment by weiwang999** [comment]
thanks
could you pls help me with another problem?
Accepting new clients...
  ref Readers: 1
Final segment pushed.
  ref Readers: 2
unref Readers: 1
Freed buffer
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Error or timeout
ret: -110
[http @ 0x2faf280] URL read error:  -107
Shut down http server.
unref Readers: 0
Freeing segment
unref Readers: 0
Freeing segment
unref Readers: 0
Freeing segment
unref Readers: 0
Freeing segment

**Comment by klaxa** [comment]
I would honestly recommend you try out my ffserver project instead. Future work will go into there. The major difference is that you need a configuration file, but it has a more reviewed codebase, albeit not bug-free.

As to your question: What exactly is the problem? It looks like you are not receiving data from the URL that can be decoded. Your issues often lack a lot of information necessary to find out what the problem is.

**Comment by weiwang999** [comment]
my problem is running server and there is an error
weiwang99@cs000061:~/mkvserver_mk2$ sudo ./server
jellyfish-110-mbps-hd-hevc.mkv
[sudo] password for weiwang99:
{
    "free": 16,
    "reserved": 0,
    "wait": 0,
    "writable": 0,
    "busy": 0
    "buffer_full": 0
    "current_read": -1
    "newest_write": 0
    "oldest_write": -1
}
Accepting new clients...
Finding video stream.
Checking stream 0
Got stream
Got params
Got type
starting new segment
Initializing segment
Initialized segment.
segment id = 0
Checking clients, thread: 0
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
  ref Readers: 1
New segment pushed.
  ref Readers: 2
unref Readers: 1
starting new segment
Initializing segment
Initialized segment.
segment id = 1
Checking clients, thread: 2
Checking clients, thread: 1
Checking clients, thread: 0
Checking clients, thread: 3
Error or timeout
ret: -110
{
    "free": 16,
    "reserved": 0,
    "wait": 0,
    "writable": 0,
    "busy": 0
    "buffer_full": 0
    "current_read": 0
    "newest_write": 0
    "oldest_write": 0
}
Accepting new clients...
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 0
Checking clients, thread: 3
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Error or timeout
ret: -110
{
    "free": 16,
    "reserved": 0,
    "wait": 0,
    "writable": 0,
    "busy": 0
    "buffer_full": 0
    "current_read": 0
    "newest_write": 0
    "oldest_write": 0
}
Accepting new clients...
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Error or timeout
ret: -110
{
    "free": 16,
    "reserved": 0,
    "wait": 0,
    "writable": 0,
    "busy": 0
    "buffer_full": 0
    "current_read": 0
    "newest_write": 0
    "oldest_write": 0
}
Accepting new clients...
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Error or timeout
ret: -110
{
    "free": 16,
    "reserved": 0,
    "wait": 0,
    "writable": 0,
    "busy": 0
    "buffer_full": 0
    "current_read": 0
    "newest_write": 0
    "oldest_write": 0
}
Accepting new clients...
  ref Readers: 1
New segment pushed.
  ref Readers: 2
unref Readers: 1
starting new segment
Initializing segment
Initialized segment.
segment id = 2
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Error or timeout
ret: -110
{
    "free": 16,
    "reserved": 0,
    "wait": 0,
    "writable": 0,
    "busy": 0
    "buffer_full": 0
    "current_read": 1
    "newest_write": 0
    "oldest_write": 1
}
Accepting new clients...
  ref Readers: 1
New segment pushed.
  ref Readers: 2
unref Readers: 1
starting new segment
Initializing segment
Initialized segment.
segment id = 3
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Error or timeout
ret: -110
{
    "free": 16,
    "reserved": 0,
    "wait": 0,
    "writable": 0,
    "busy": 0
    "buffer_full": 0
    "current_read": 2
    "newest_write": 0
    "oldest_write": 2
}
Accepting new clients...
Checking clients, thread: 1
Checking clients, thread: 3
Checking clients, thread: 2
Checking clients, thread: 0
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Error or timeout
ret: -110
{
    "free": 16,
    "reserved": 0,
    "wait": 0,
    "writable": 0,
    "busy": 0
    "buffer_full": 0
    "current_read": 2
    "newest_write": 0
    "oldest_write": 2
}
Accepting new clients...
  ref Readers: 1
Final segment pushed.
  ref Readers: 2
unref Readers: 1
Freed buffer
Checking clients, thread: 1
Checking clients, thread: 2
Checking clients, thread: 3
Checking clients, thread: 0
Error or timeout
ret: -110
[http @ 0x2faf280] URL read error:  -107
Shut down http server.
unref Readers: 0
Freeing segment
unref Readers: 0
Freeing segment
unref Readers: 0
Freeing segment
unref Readers: 0
Freeing segment
