### ISSUE TITLE
Can't compile it on Ubuntu 18.04

### ISSUE THREAD

**Issue by Nottt** [klaxa/mkvserver_mk2#20]
I found your software googling about ffserver...seems to be a awesome software...but I can't build it?

I cloned the repo, but when I do `make`:

```
cc -g -Wall `pkg-config --cflags libavformat libavcodec libavutil` -pthread -c segment.c
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
In file included from segment.c:2:0:
segment.h:4:10: fatal error: libavformat/avformat.h: No such file or directory
 #include <libavformat/avformat.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:15: recipe for target 'segment.o' failed
make: *** [segment.o] Error 1
```

This software seems to be the perfect software to put into a docker container. I could help with that if you give me instructions...

**Comment by ShadyBoukhary** [comment]
You need to install all those missing packages before trying to compile.

**Comment by Nottt** [comment]
Is there a list of dependencies somewhere?

**Comment by ShadyBoukhary** [comment]
Not sure. But I installed all of them by just installing ffmpeg.

**Comment by Nottt** [comment]
I did a quick test with a ubuntu 18.04 docker. 

Did apt install `ffmpeg make pkg-config git -y` and still fails... If we had a list of dependencies it'd be easier....

About ffmpeg, don't install ffmpeg using your repository...use static builds since the repo versions are usually ancient

**Comment by Nottt** [comment]
Everything you need to compile is this: `apt install make pkg-config git libavformat-dev -y`

One line to compile:

```
apt update && \
apt install make pkg-config git libavformat-dev -y && \
git clone https://github.com/klaxa/mkvserver_mk2 && \
cd mkv* && make

```
You can then use your compiled file in any system, and just need to `apt install libavformat57 -y`

This should fix https://github.com/klaxa/mkvserver_mk2/issues/12, https://github.com/klaxa/mkvserver_mk2/issues/11, https://github.com/klaxa/mkvserver_mk2/issues/9.

Is there a reason there is a compiled binary to download and instead require us to build from source? It seems to work fine If I just take my file I compiled inside docker and run it somewhere else....
