### ISSUE TITLE
[tcp @ 0xb4e79190] Failed to resolve hostname 0: No address associated with hostname

### ISSUE THREAD

**Issue by ghost** [klaxa/mkvserver_mk2#30]
Hello, I builded this repo in termux. arm cpu

Running the command `tsudo ./server somevid.mkv`, I got this error:
`[tcp @ 0xb4e79190] Failed to resolve hostname 0: No address associated with hostname`
Is this normal?

If you need elaboration, I could reply.

**Comment by klaxa** [comment]
That should be listening on all interfaces. You can try changing ainfo.out_uri at https://github.com/klaxa/mkvserver_mk2/blob/c62abc30f4cca6147ddc732570b30fcb4bee30ec/server2.c#L435 to "http://0.0.0.0:8080". If that doesn't work either you could try a bound address or localhost (127.0.0.1). Note that the server will only be available on those bound interfaces then.

**Comment by ghost** [comment]
Thanks! It's listening now.
