### ISSUE TITLE
README doesn't contain advice on how to minimize lag

### ISSUE THREAD

**Issue by afontenot** [klaxa/mkvserver_mk2#4]
I'm filing this as a documentation bug, rather than a bug with the code, which I assume supports this.

I am / was considering using this project for a near-realtime streaming application, but I'm seeing lag of about 60 seconds between the source (screen recording with ffmpeg) and seeing the result on VLC. So far as I can tell, almost none of this is network lag. I've tried tinkering with the buffering constants in the source without success. Is there any way to get lag down below 5 seconds or so?

**Comment by klaxa** [comment]
Hi and thanks for the feedback!

The delay depends highly on the size of your GOPs (-g option in ffmpeg). The video is split along the GOPs and only every GOP that has been finished reading will be sent out to clients, meaning there is usually a delay of at least one GOP before sending it to clients. You can reduce the delay by decreasing the size of the GOPs by setting a lower -g value in your ffmpeg command.

Other factors that can affect streaming delay is the BUFFER_SECS constant in server2.c and BUFFER_SEGMENTS in publisher.h.

BUFFER_SECS denotes how many seconds of an input should be read as fast as possible (this should make no difference for streamed files) before switching to real-time reading depending on the timestamps of the file.

BUFFER_SEGMENTS contains the number of segments (GOPs) the publisher keeps to send to new clients. These are up to BUFFER_SEGMENTS old segments.

These two mechanics were introduced to reduce startup lag in clients and generally give them more video to buffer.

To decrease delay as much as possible (but also possibly introduce stuttering in the player) it should be safe to set both of these to 0.

I hope that helps!

**Comment by klaxa** [comment]
I hope the addition to the readme brings across this point. If not, feel free to reopen the issue and discuss it some more.
I have also already an idea of how a lower latency version could work like. Maybe I'll make some time to work on it.
